// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';

import { TestDialogComponent } from './home/test-dialog';

import { AboutDialog } from './about/about.dialog';

import { SampleCrudPreferencesComponent } from './preferences/sample/sample-crud-preference';

import { HomeComponent } from './home/home.component';

import { SamplePreferencesComponent } from './preferences/sample/sample-preference';

import { PreferencesDialog } from './preferences/preferences-dialog';

import { PageNotFoundComponent } from './page-not-found/page-not-found.component';

export const localRoutes: Routes = [
  {
    path: '',
    redirectTo: 'home',
    pathMatch: 'full',
  },
  {
    path: 'test-dialog',
    component: TestDialogComponent,
    children: [],
  },
  {
    path: 'about-dialog',
    component: AboutDialog,
    children: [],
  },
  {
    path: 'crud-preferences',
    component: SampleCrudPreferencesComponent,
    children: [],
  },
  {
    path: 'home',
    component: HomeComponent,
    children: [],
  },
  {
    path: 'preferences-1',
    component: SamplePreferencesComponent,
    children: [],
  },
  {
    path: 'preferences-dialog',
    component: PreferencesDialog,
    children: [],
  },
  {
    path: 'private-portal',
    loadChildren: () =>
      import('./private-portal/private-portal.module').then(
        (m) => m.PrivatePortalModule,
      ),
  },
  {
    path: 'public-portal',
    loadChildren: () =>
      import('./public-portal/public-portal.module').then(
        (m) => m.PublicPortalModule,
      ),
  },

  {
    path: '**',
    component: PageNotFoundComponent,
  },
];
