// DO NOT TOUCH THIS FILE
// GENERATED BY MICROFRONTEND GENERATOR V1.0

import { Routes, RouterModule } from '@angular/router';

import { TestDialogComponent } from './home/test-dialog';

import { AboutDialog } from './about/about.dialog';

import { InspectorPageComponent } from './feature-browser/feature-browser.component';

import { HomeComponent } from './home/home.component';

import { PreferencesDialog } from './preferences/preferences-dialog';

import { SampleCrudPreferencesComponent } from './preferences/sample/sample-crud-preference';

import { SamplePreferencesComponent } from './preferences/sample/sample-preference';

import { ShowcasePageComponent } from './showcase-browser/showcase-browser.component';

import { DialogsShowcaseComponent } from './showcases/dialogs/dialogs-showcase.component';

import { SampleShowcaseComponent } from './showcases/sample/sample-showcase.component';

import { PageNotFoundComponent } from './page-not-found/page-not-found.component';

export const localRoutes: Routes = [
  {
    path: '',
    redirectTo: 'home',
    pathMatch: 'full',
  },
  {
    path: 'test-dialog',
    component: TestDialogComponent,
    children: [],
  },
  {
    path: 'about-dialog',
    component: AboutDialog,
    children: [],
  },
  {
    path: 'feature-browser',
    component: InspectorPageComponent,
    children: [],
  },
  {
    path: 'home',
    component: HomeComponent,
    children: [],
  },
  {
    path: 'preferences-dialog',
    component: PreferencesDialog,
    children: [],
  },
  {
    path: 'private-portal',
    loadChildren: () =>
      import('./private-portal/private-portal.module').then(
        (m) => m.PrivatePortalModule,
      ),
  },
  {
    path: 'public-portal',
    loadChildren: () =>
      import('./public-portal/public-portal.module').then(
        (m) => m.PublicPortalModule,
      ),
  },
  {
    path: 'sample-crud-preferences',
    component: SampleCrudPreferencesComponent,
    children: [],
  },
  {
    path: 'sample-preferences',
    component: SamplePreferencesComponent,
    children: [],
  },
  {
    path: 'showcases',
    component: ShowcasePageComponent,
    children: [
      {
        path: 'dialogs-showcase',
        component: DialogsShowcaseComponent,
        children: [],
      },

      {
        path: 'sample-showcase',
        component: SampleShowcaseComponent,
        children: [],
      },
    ],
  },

  {
    path: '**',
    component: PageNotFoundComponent,
  },
];
